name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - tpcarman
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: >-
        Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: command-line-input
    attributes:
      label: Command-line input
      description: >-
        Please provide the command line input you are using to run AsBuiltReport. Please ensure that you obscure any sensitive information.
      placeholder: New-AsBuiltReport -Report VMware.vSphere -Target xxxxxxx -Format Word,HTML -OutputFolderPath 'C:\Users\..\Documents' -AsBuiltConfigFilePath 'C:\Users\..\AsBuiltReport\AsBuiltReport.json' -ReportConfigFilePath 'C:\Users\..\AsBuiltReport\AsBuiltReport.VMware.vSphere.json' -EnableHealthCheck -Verbose
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Please provide a detailed list of steps to reproduce the bug.
      placeholder: |-
        1. ....
        2. ....
        3. ....
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: >-
        Please provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        Please attach any screenshots to help explain the problem.  Please ensure that you obscure any sensitive information.
      placeholder: |-
        Drag and drop screenshots here.
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: Please provide information about the operating system are you using.
      placeholder: macOS Big Sur, Windows 10, Ubuntu 20.04 LTS
    validations:
      required: true
  - type: textarea
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: Please provide information about the PowerShell version you are using. Please provide the output from the following PowerShell command `$PSVersionTable`.
      placeholder: $PSVersionTable
    validations:
      required: true
  - type: textarea
    id: powershell-modules
    attributes:
      label: PowerShell Modules
      description: Please provide information about the PowerShell modules are you using. Please provide the output from the following PowerShell command `Get-Module -ListAvailable @("AsBuiltReport.Core";"AsBuiltReport.VMware.vSphere";"PSPKI";"PScriboCharts";"PScribo") | Select Name, Version`
      placeholder: Get-Module -ListAvailable @("AsBuiltReport.Core";"AsBuiltReport.VMware.vSphere";"PScribo") | Select Name, Version
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: This field is optional. You may provide additional context for the bug you wish to report. You may wish to include links to any related [issues](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/issues) or other relevant information.
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you are unsure of what a specific requirement means, please follow the links to learn about it and understand why it is necessary before submitting.
      options:
        - label: >-
            I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
          required: true
        - label: >-
            I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig),
            and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
          required: true
        - label: >-
            I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/issues) before submitting this bug report.
          required: true
