name: Pester Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  pester-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set PSRepository to Trusted for PowerShell Gallery
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

      - name: Install required modules
        shell: pwsh
        run: |
          Install-Module -Name AsBuiltReport.Core -Repository PSGallery -Force -AllowClobber -Scope CurrentUser
          Install-Module -Name PScribo -Repository PSGallery -Force -AllowClobber -Scope CurrentUser
          Install-Module -Name Pester -MinimumVersion 5.0.0 -Repository PSGallery -Force -AllowClobber -Scope CurrentUser
          Install-Module -Name PSScriptAnalyzer -Repository PSGallery -Force -AllowClobber -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: |
          .\Tests\Invoke-Tests.ps1 -OutputFormat NUnitXml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pester Tests
          path: Tests/testResults.xml
          reporter: dotnet-nunit
          fail-on-error: true
